import { RoutineTemplate } from '../data/foodDatabase';
import { WorkoutRoutine } from '../data/mockData';
import { apiRequest } from './api';
import { decodeHtmlEntities } from '../utils/html';

import { ApiRoutineTemplate, apiRoutineToRoutineTemplate } from './mappers';

export async function listRoutineTemplatesFromApi(goal?: string, level?: string): Promise<RoutineTemplate[]> {
  const params = new URLSearchParams();
  if (goal) params.set('goal', goal);
  if (level) params.set('level', level);

  const suffix = params.toString() ? `?${params.toString()}` : '';
  const routines = await apiRequest<ApiRoutineTemplate[]>(`/routines/templates${suffix}`);
  return routines.map(apiRoutineToRoutineTemplate);
}



export interface RoutineTemplatePayload {
  title: string;
  target_goal: string;
  level: string;
  days_per_week: number;
  description?: string;
  trainer_rationale?: string;
  payload_json?: string;
}

export async function createRoutineTemplateInApi(payload: RoutineTemplatePayload): Promise<RoutineTemplate> {
  const row = await apiRequest<ApiRoutineTemplate>('/routines/templates', {
    method: 'POST',
    body: JSON.stringify({ ...payload, payload_json: payload.payload_json || '{}' }),
  });
  return apiRoutineToRoutineTemplate(row);
}

interface ApiAssignedRoutine {
  id: number;
  client_id: number;
  trainer_id?: number | null;
  title: string;
  objective: string;
  payload_json: string;
  active: number;
  created_at: string;
}

export interface RoutineDeliveryHealth {
  delivery_ready: boolean;
  blocking_reasons: string[];
  client: {
    id: number;
    name: string;
    email: string;
    status: string;
    duplicate_email_user_ids: number[];
  };
  routine: {
    active_count: number;
    id: number | null;
    title: string | null;
    payload_chars: number;
    payload_valid: boolean;
    payload_error: string;
    day_count: number;
    exercise_count: number;
  };
  membership: {
    available: boolean;
    status: string;
    restricted: boolean;
    pending_payments: number;
    next_payment_due: string | null;
    error: string;
  };
  client_endpoint: string;
}

function apiAssignedToWorkoutRoutine(row: ApiAssignedRoutine): WorkoutRoutine {
  let parsed: Partial<WorkoutRoutine> = {};
  try {
    parsed = JSON.parse(row.payload_json || '{}');
  } catch {
    try {
      parsed = JSON.parse(decodeHtmlEntities(row.payload_json || '{}'));
    } catch {
      parsed = {};
    }
  }
  return {
    id: String(row.id),
    clientId: String(row.client_id),
    clientName: parsed.clientName || `Cliente ${row.client_id}`,
    title: row.title,
    objective: row.objective,
    generatedDate: row.created_at.split('T')[0],
    days: parsed.days || [],
    specialistAdvice: parsed.specialistAdvice || 'Rutina asignada por entrenador Imperial Fitness.',
    autoGenerated: parsed.autoGenerated,
    safetyReviewRequired: parsed.safetyReviewRequired,
    safetySummary: parsed.safetySummary,
    excludedExercisesCount: parsed.excludedExercisesCount,
    publishedAt: parsed.publishedAt,
    publishedBy: parsed.publishedBy,
    presetId: parsed.presetId,
    presetVersion: parsed.presetVersion,
    presetAudience: parsed.presetAudience,
    structureLocked: parsed.structureLocked,
    weeklyVolumeSummary: parsed.weeklyVolumeSummary,
    progressionGuide: parsed.progressionGuide,
  };
}

export async function listAssignedRoutinesFromApi(clientId?: string): Promise<WorkoutRoutine[]> {
  const suffix = clientId ? `?client_id=${encodeURIComponent(clientId)}` : '';
  const rows = await apiRequest<ApiAssignedRoutine[]>(`/routines/assigned${suffix}`, clientId ? { cache: 'no-store' } : {});
  return rows.map(apiAssignedToWorkoutRoutine);
}

export async function getMyAssignedRoutineFromApi(): Promise<WorkoutRoutine | null> {
  const row = await apiRequest<ApiAssignedRoutine | null>('/routines/assigned/my-routine', { cache: 'no-store' });
  return row ? apiAssignedToWorkoutRoutine(row) : null;
}

export async function getClientRoutineDeliveryHealthFromApi(clientId: string): Promise<RoutineDeliveryHealth> {
  return apiRequest<RoutineDeliveryHealth>(
    `/routines/assigned/client-health/${encodeURIComponent(clientId)}`,
    { cache: 'no-store' },
  );
}

export async function createAssignedRoutineInApi(routine: WorkoutRoutine): Promise<WorkoutRoutine> {
  const row = await apiRequest<ApiAssignedRoutine>('/routines/assigned', {
    method: 'POST',
    body: JSON.stringify({
      client_id: Number(routine.clientId),
      title: routine.title,
      objective: routine.objective,
      payload_json: JSON.stringify(routine),
      active: 1,
    }),
  });
  return apiAssignedToWorkoutRoutine(row);
}

export async function updateAssignedRoutineInApi(routineId: string, updates: Partial<WorkoutRoutine>): Promise<WorkoutRoutine> {
  const body: Record<string, unknown> = {};
  if (updates.title !== undefined) body.title = updates.title;
  if (updates.objective !== undefined) body.objective = updates.objective;
  if (updates.days !== undefined || updates.specialistAdvice !== undefined || updates.clientName !== undefined) {
    body.payload_json = JSON.stringify(updates);
  }
  const row = await apiRequest<ApiAssignedRoutine>(`/routines/assigned/${encodeURIComponent(routineId)}`, {
    method: 'PUT',
    body: JSON.stringify(body),
  });
  return apiAssignedToWorkoutRoutine(row);
}

export async function deactivateAssignedRoutineInApi(routineId: string): Promise<void> {
  await apiRequest<{ ok: boolean }>(`/routines/assigned/${encodeURIComponent(routineId)}`, {
    method: 'DELETE',
  });
}
