import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react';
import { Activity, AlertTriangle, CheckCircle2, ChevronDown, ChevronUp, ClipboardCheck, Download, Dumbbell, HeartPulse, Loader2, Salad, Scale, Send } from 'lucide-react';
import { clearLiteSession, downloadLitePdf, exchangeLiteLink, getLiteCheckins, getLiteIntake, getLiteMe, getLitePlans, getLiteSession, saveLiteIntake, submitLiteCheckin, type LiteClient, type LiteIntake, type LitePlans } from '../services/liteService';

const Card = ({ children, className='' }: { children: ReactNode; className?: string }) => <section className={`rounded-3xl border border-neutral-800 bg-neutral-950/95 p-5 shadow-xl ${className}`}>{children}</section>;

function RoutineView({ plan }: { plan: NonNullable<LitePlans['routine']> }) {
  const data = plan.content as any;
  const days = Array.isArray(data?.days) ? data.days : [];
  return <div className="space-y-4">
    {days.map((day:any, idx:number) => <div key={idx} className="rounded-2xl border border-neutral-800 bg-neutral-900/60 p-4">
      <div className="mb-3"><p className="font-black text-white">{day.day || day.name || day.title || `Sesión ${idx+1}`}</p><p className="text-xs text-neutral-400">{day.focus || ''}</p></div>
      <div className="space-y-2">{(day.exercises || []).map((ex:any, i:number) => <div key={i} className="rounded-xl bg-black/40 p-3">
        <p className="text-sm font-bold text-white">{ex.name || 'Ejercicio'}</p>
        <p className="mt-1 text-xs text-neutral-300">{ex.sets ? `${ex.sets} series` : ''}{ex.reps ? ` · ${ex.reps} reps` : ''}{ex.rest ? ` · descanso ${ex.rest}` : ''}{ex.targetRir || ex.rir ? ` · RIR ${ex.targetRir || ex.rir}` : ''}</p>
        {ex.notes && <p className="mt-1 text-xs text-neutral-500">{ex.notes}</p>}
      </div>)}</div>
    </div>)}
    {!days.length && <p className="text-sm text-neutral-400">Tu coach aún no ha publicado el detalle del entrenamiento.</p>}
  </div>;
}

function DietView({ plan }: { plan: NonNullable<LitePlans['diet']> }) {
  const meals:any[] = Array.isArray(plan.content) ? plan.content : [];
  return <div className="space-y-4">
    <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
      {[['kcal',plan.calories],['Proteína',plan.protein ? `${plan.protein} g` : undefined],['Carbos',plan.carbs ? `${plan.carbs} g` : undefined],['Grasas',plan.fat ? `${plan.fat} g` : undefined]].map(([k,v]) => <div key={String(k)} className="rounded-xl bg-neutral-900 p-3"><p className="text-[10px] uppercase text-neutral-500">{k}</p><p className="font-black text-white">{v ?? '—'}</p></div>)}
    </div>
    {meals.map((meal:any,idx:number)=><div key={idx} className="rounded-2xl border border-neutral-800 bg-neutral-900/60 p-4"><p className="font-black text-white">{meal.name || meal.title || `Comida ${idx+1}`}</p><div className="mt-2 space-y-1">{(meal.items || meal.foods || []).map((item:any,i:number)=><p key={i} className="text-sm text-neutral-300">• {item.currentName || item.name || item.food || 'Alimento'} {item.amountGrams || item.grams || item.portion ? `— ${item.amountGrams || item.grams || item.portion}${typeof (item.amountGrams || item.grams) === 'number' ? ' g' : ''}` : ''}</p>)}</div></div>)}
    {plan.notes && <p className="rounded-xl bg-neutral-900 p-3 text-xs text-neutral-300">{plan.notes}</p>}
  </div>;
}

export function LitePortal() {
  const [client,setClient]=useState<LiteClient|null>(null); const [plans,setPlans]=useState<LitePlans|null>(null); const [history,setHistory]=useState<any[]>([]); const [intakeDone,setIntakeDone]=useState(false);
  const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [open,setOpen]=useState<'intake'|'checkin'|'routine'|'diet'|'evolution'|null>('checkin'); const [saving,setSaving]=useState(false); const [saved,setSaved]=useState(false); const [intakeSaving,setIntakeSaving]=useState(false);
  const [form,setForm]=useState({weight:'',training_sessions:'',nutrition_adherence:'',energy:'',sleep_hours:'',hunger:'',stress:'',pain_present:false,pain_score:'',pain_area:'',pain_trigger:'',notes:''});
  const [intake,setIntake]=useState<LiteIntake>({medical_clearance_needed:false,chest_pain_or_fainting:false,pregnancy_or_lactation:false,diabetes:false,kidney_disease:false,hypertension:false,eating_disorder_history:false,digestive_condition:false,food_allergies:'',medications:'',injuries_or_surgeries:'',dietary_preferences:'',foods_disliked:'',cooking_access:'normal',budget_level:'medium',notes:''});
  const linkToken=useMemo(()=>{
    const fragment = new URLSearchParams(location.hash.replace(/^#/, '')).get('token') || '';
    if (fragment) return fragment;
    const parts=location.pathname.split('/').filter(Boolean);
    return parts[0]==='lite' && parts[1] ? parts[1] : '';
  },[]);

  useEffect(()=>{ let alive=true; (async()=>{ try {
    if (linkToken) { history.replaceState({},'', '/lite'); const ex=await exchangeLiteLink(linkToken); if (!alive) return; setClient(ex.client); }
    else if (!getLiteSession()) throw new Error('Este enlace no tiene una sesión activa. Solicita un nuevo enlace a tu coach.');
    const [me,p,h,i]=await Promise.all([getLiteMe(),getLitePlans(),getLiteCheckins(),getLiteIntake()]); if (!alive) return; setClient(me); setPlans(p); setHistory(h); setIntakeDone(i.completed); if(i.data)setIntake(prev=>({...prev,...i.data}));
  } catch(e:any) { clearLiteSession(); if(alive)setError(e?.message || 'No fue posible abrir tu seguimiento.'); } finally { if(alive)setLoading(false); } })(); return()=>{alive=false}; },[linkToken]);

  const submit=async(e:FormEvent)=>{e.preventDefault();setSaving(true);setSaved(false);setError('');try{await submitLiteCheckin({weight:form.weight?Number(form.weight):undefined,training_sessions:form.training_sessions?Number(form.training_sessions):undefined,nutrition_adherence:form.nutrition_adherence?Number(form.nutrition_adherence):undefined,energy:form.energy?Number(form.energy):undefined,sleep_hours:form.sleep_hours?Number(form.sleep_hours):undefined,hunger:form.hunger?Number(form.hunger):undefined,stress:form.stress?Number(form.stress):undefined,pain_present:form.pain_present,pain_score:form.pain_score?Number(form.pain_score):undefined,pain_area:form.pain_area,pain_trigger:form.pain_trigger,notes:form.notes});setSaved(true);setHistory(await getLiteCheckins());setTimeout(()=>setSaved(false),4000);}catch(e:any){setError(e?.message||'No se pudo guardar.')}finally{setSaving(false)}};
  const submitIntake=async(e:FormEvent)=>{e.preventDefault();setIntakeSaving(true);setError('');setNotice('');try{const r=await saveLiteIntake(intake);setIntakeDone(true);setMsgFromIntake(r.flags);setOpen('checkin');}catch(e:any){setError(e?.message||'No se pudo guardar el cuestionario.')}finally{setIntakeSaving(false)}};
  const setMsgFromIntake=(flags:string[])=>setNotice(flags.length ? 'Cuestionario guardado. Tu coach verá las alertas y revisará el plan antes de publicarlo.' : 'Cuestionario guardado correctamente.');
  if(loading)return <div className="min-h-screen bg-black text-white flex items-center justify-center"><Loader2 className="h-9 w-9 animate-spin text-red-500"/></div>;
  if(error && !client)return <div className="min-h-screen bg-black text-white flex items-center justify-center px-5"><Card className="max-w-md text-center"><AlertTriangle className="mx-auto h-10 w-10 text-amber-400"/><h1 className="mt-4 text-xl font-black">No pudimos abrir tu enlace</h1><p className="mt-2 text-sm text-neutral-400">{error}</p></Card></div>;

  const SectionButton=({id,icon:Icon,title,subtitle}:{id:any;icon:any;title:string;subtitle:string})=><button onClick={()=>setOpen(open===id?null:id)} className="flex w-full items-center gap-3 rounded-2xl border border-neutral-800 bg-neutral-950 p-4 text-left"><span className="rounded-xl bg-red-950/50 p-2 text-red-400"><Icon className="h-5 w-5"/></span><span className="min-w-0 flex-1"><span className="block font-black text-white">{title}</span><span className="block text-xs text-neutral-500">{subtitle}</span></span>{open===id?<ChevronUp className="h-4 w-4 text-neutral-500"/>:<ChevronDown className="h-4 w-4 text-neutral-500"/>}</button>;
  const Select=({name,label,options}:{name:keyof typeof form;label:string;options:[string,string][]})=><label className="block"><span className="mb-1 block text-xs font-bold text-neutral-400">{label}</span><select value={String(form[name])} onChange={e=>setForm(f=>({...f,[name]:e.target.value}))} className="w-full rounded-xl border border-neutral-800 bg-black px-3 py-3 text-sm text-white"><option value="">Opcional</option>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>;

  return <main className="min-h-screen bg-black text-white"><div className="mx-auto max-w-2xl px-4 py-6 sm:py-10">
    <header className="mb-6"><div className="text-xs font-black uppercase tracking-[0.28em] text-red-500">Imperial Fitness Lite</div><h1 className="mt-2 text-3xl font-black">Hola, {client?.name?.split(' ')[0]}</h1><p className="mt-2 text-sm text-neutral-400">Tu seguimiento, entrenamiento y alimentación en un solo enlace. Sin instalar nada.</p></header>
    {error && <div className="mb-4 rounded-2xl border border-red-900/60 bg-red-950/30 p-3 text-sm text-red-200">{error}</div>}
    {notice && <div className="mb-4 rounded-2xl border border-amber-900/60 bg-amber-950/25 p-3 text-sm text-amber-100">{notice}</div>}
    {saved && <div className="mb-4 flex items-center gap-2 rounded-2xl border border-emerald-900/60 bg-emerald-950/30 p-3 text-sm text-emerald-200"><CheckCircle2 className="h-4 w-4"/>Seguimiento enviado a tu coach.</div>}
    <div className="space-y-3">
      <SectionButton id="intake" icon={HeartPulse} title={intakeDone ? "Cuestionario inicial" : "Completar cuestionario inicial"} subtitle={intakeDone ? "Puedes actualizarlo si algo cambió" : "Salud, lesiones, preferencias y contexto"}/>
      {open==='intake' && <Card><form onSubmit={submitIntake} className="space-y-4">
        <div className="rounded-xl border border-amber-900/50 bg-amber-950/20 p-3 text-xs text-amber-100">Este cuestionario ayuda a tu coach a detectar situaciones que requieren revisión profesional. No sustituye una valoración médica o nutricional.</div>
        <div className="grid gap-2 sm:grid-cols-2">
          {[['medical_clearance_needed','Un profesional me indicó que debo tener autorización para entrenar'],['chest_pain_or_fainting','He tenido dolor en el pecho, desmayo o mareos importantes'],['pregnancy_or_lactation','Embarazo o lactancia'],['diabetes','Diabetes'],['kidney_disease','Enfermedad renal'],['hypertension','Hipertensión'],['eating_disorder_history','Antecedente de trastorno de la conducta alimentaria'],['digestive_condition','Condición digestiva relevante']].map(([key,label])=><label key={key} className="flex items-start gap-2 rounded-xl border border-neutral-800 p-3 text-xs text-neutral-300"><input className="mt-0.5" type="checkbox" checked={Boolean((intake as any)[key])} onChange={e=>setIntake(v=>({...v,[key]:e.target.checked}))}/><span>{label}</span></label>)}
        </div>
        <div className="grid gap-3 sm:grid-cols-2">
          <label className="block"><span className="mb-1 block text-xs font-bold text-neutral-400">Alergias o intolerancias</span><input value={intake.food_allergies} onChange={e=>setIntake(v=>({...v,food_allergies:e.target.value}))} className="w-full rounded-xl border border-neutral-800 bg-black px-3 py-3"/></label>
          <label className="block"><span className="mb-1 block text-xs font-bold text-neutral-400">Medicamentos relevantes</span><input value={intake.medications} onChange={e=>setIntake(v=>({...v,medications:e.target.value}))} className="w-full rounded-xl border border-neutral-800 bg-black px-3 py-3"/></label>
          <label className="block sm:col-span-2"><span className="mb-1 block text-xs font-bold text-neutral-400">Lesiones, cirugías o molestias</span><textarea rows={2} value={intake.injuries_or_surgeries} onChange={e=>setIntake(v=>({...v,injuries_or_surgeries:e.target.value}))} className="w-full rounded-xl border border-neutral-800 bg-black px-3 py-3"/></label>
          <label className="block"><span className="mb-1 block text-xs font-bold text-neutral-400">Preferencias alimentarias</span><input value={intake.dietary_preferences} onChange={e=>setIntake(v=>({...v,dietary_preferences:e.target.value}))} className="w-full rounded-xl border border-neutral-800 bg-black px-3 py-3"/></label>
          <label className="block"><span className="mb-1 block text-xs font-bold text-neutral-400">Alimentos que no te gustan</span><input value={intake.foods_disliked} onChange={e=>setIntake(v=>({...v,foods_disliked:e.target.value}))} className="w-full rounded-xl border border-neutral-800 bg-black px-3 py-3"/></label>
          <label className="block"><span className="mb-1 block text-xs font-bold text-neutral-400">Acceso para cocinar</span><select value={intake.cooking_access} onChange={e=>setIntake(v=>({...v,cooking_access:e.target.value as any}))} className="w-full rounded-xl border border-neutral-800 bg-black px-3 py-3"><option value="limited">Limitado</option><option value="normal">Normal</option><option value="full">Amplio</option></select></label>
          <label className="block"><span className="mb-1 block text-xs font-bold text-neutral-400">Presupuesto de alimentación</span><select value={intake.budget_level} onChange={e=>setIntake(v=>({...v,budget_level:e.target.value as any}))} className="w-full rounded-xl border border-neutral-800 bg-black px-3 py-3"><option value="low">Ajustado</option><option value="medium">Medio</option><option value="flexible">Flexible</option></select></label>
        </div>
        <button disabled={intakeSaving} className="flex w-full items-center justify-center gap-2 rounded-xl bg-neutral-100 px-4 py-3 font-black text-black disabled:opacity-60">{intakeSaving?<Loader2 className="h-4 w-4 animate-spin"/>:<CheckCircle2 className="h-4 w-4"/>}Guardar cuestionario</button>
      </form></Card>}
      <SectionButton id="checkin" icon={ClipboardCheck} title="Registrar seguimiento" subtitle="Tarda aproximadamente un minuto"/>
      {open==='checkin' && <Card><form onSubmit={submit} className="space-y-4">
        <div className="rounded-xl bg-neutral-900 p-3 text-xs text-neutral-400">El peso es opcional. Tu coach puede pedirlo con la frecuencia que tenga sentido para tu proceso.</div>
        <div className="grid grid-cols-2 gap-3"><label className="block"><span className="mb-1 block text-xs font-bold text-neutral-400">Peso kg (opcional)</span><input type="number" step="0.1" value={form.weight} onChange={e=>setForm(f=>({...f,weight:e.target.value}))} className="w-full rounded-xl border border-neutral-800 bg-black px-3 py-3"/></label><label className="block"><span className="mb-1 block text-xs font-bold text-neutral-400">Entrenamientos realizados</span><input type="number" min="0" max="14" value={form.training_sessions} onChange={e=>setForm(f=>({...f,training_sessions:e.target.value}))} className="w-full rounded-xl border border-neutral-800 bg-black px-3 py-3"/></label></div>
        <div className="grid grid-cols-2 gap-3"><Select name="energy" label="Energía" options={[["1","Muy baja"],["2","Baja"],["3","Normal"],["4","Buena"],["5","Excelente"]]}/><Select name="stress" label="Estrés" options={[["1","Muy bajo"],["2","Bajo"],["3","Medio"],["4","Alto"],["5","Muy alto"]]}/></div>
        <div className="grid grid-cols-2 gap-3"><Select name="hunger" label="Hambre/saciedad" options={[["1","Muy poca hambre"],["2","Poca"],["3","Normal"],["4","Alta"],["5","Muy alta"]]}/><div className="rounded-xl bg-neutral-900 p-3 text-xs text-neutral-500">Responde según tu promedio reciente; no necesitas medir todo a diario.</div></div>
        <div className="grid grid-cols-2 gap-3"><label className="block"><span className="mb-1 block text-xs font-bold text-neutral-400">Sueño promedio (h)</span><input type="number" step="0.5" min="0" max="24" value={form.sleep_hours} onChange={e=>setForm(f=>({...f,sleep_hours:e.target.value}))} className="w-full rounded-xl border border-neutral-800 bg-black px-3 py-3"/></label><label className="block"><span className="mb-1 block text-xs font-bold text-neutral-400">Adherencia alimentación %</span><input type="number" min="0" max="100" value={form.nutrition_adherence} onChange={e=>setForm(f=>({...f,nutrition_adherence:e.target.value}))} className="w-full rounded-xl border border-neutral-800 bg-black px-3 py-3"/></label></div>
        <label className="flex items-center gap-3 rounded-xl border border-neutral-800 p-3"><input type="checkbox" checked={form.pain_present} onChange={e=>setForm(f=>({...f,pain_present:e.target.checked}))}/><span><span className="block text-sm font-bold">¿Tienes dolor o una molestia importante?</span><span className="text-xs text-neutral-500">Si es sí, tu coach recibirá una alerta.</span></span></label>
        {form.pain_present && <div className="grid gap-3 rounded-2xl border border-amber-900/50 bg-amber-950/15 p-4 sm:grid-cols-2"><label><span className="mb-1 block text-xs font-bold text-amber-200">Intensidad 0–10 *</span><input required type="number" min="0" max="10" value={form.pain_score} onChange={e=>setForm(f=>({...f,pain_score:e.target.value}))} className="w-full rounded-xl border border-neutral-800 bg-black px-3 py-3"/></label><label><span className="mb-1 block text-xs font-bold text-amber-200">Zona *</span><input required value={form.pain_area} onChange={e=>setForm(f=>({...f,pain_area:e.target.value}))} placeholder="Ej. rodilla derecha" className="w-full rounded-xl border border-neutral-800 bg-black px-3 py-3"/></label><label className="sm:col-span-2"><span className="mb-1 block text-xs font-bold text-amber-200">¿Qué movimiento la provoca?</span><input value={form.pain_trigger} onChange={e=>setForm(f=>({...f,pain_trigger:e.target.value}))} className="w-full rounded-xl border border-neutral-800 bg-black px-3 py-3"/></label></div>}
        <label className="block"><span className="mb-1 block text-xs font-bold text-neutral-400">Algo que quieras contarle a tu coach</span><textarea rows={3} value={form.notes} onChange={e=>setForm(f=>({...f,notes:e.target.value}))} className="w-full rounded-xl border border-neutral-800 bg-black px-3 py-3"/></label>
        <button disabled={saving} className="flex w-full items-center justify-center gap-2 rounded-xl bg-red-600 px-4 py-3 font-black hover:bg-red-500 disabled:opacity-60">{saving?<Loader2 className="h-4 w-4 animate-spin"/>:<Send className="h-4 w-4"/>}Enviar a mi coach</button>
      </form></Card>}
      <SectionButton id="routine" icon={Dumbbell} title="Ver entrenamiento" subtitle={plans?.routine ? `${plans.routine.title}${plans.routine.version?` · v${plans.routine.version}`:''}` : 'Tu coach aún no ha publicado uno'}/>
      {open==='routine' && <Card>{plans?.routine ? <><div className="mb-4 flex items-center justify-between gap-3"><div><h2 className="font-black">{plans.routine.title}</h2>{plans.routine.objective&&<p className="text-xs text-neutral-400">{plans.routine.objective}</p>}</div>{plans.routine.publication_id&&<button onClick={()=>downloadLitePdf(plans.routine!.publication_id!,`entrenamiento-imperial-v${plans.routine!.version||1}.pdf`)} className="flex items-center gap-1 rounded-lg border border-neutral-700 px-3 py-2 text-xs font-bold"><Download className="h-4 w-4"/>PDF</button>}</div><RoutineView plan={plans.routine}/></> : <p className="text-sm text-neutral-400">Aún no hay un entrenamiento publicado.</p>}</Card>}
      <SectionButton id="diet" icon={Salad} title="Ver alimentación" subtitle={plans?.diet ? `${plans.diet.title}${plans.diet.version?` · v${plans.diet.version}`:''}` : 'Tu coach aún no ha publicado una'}/>
      {open==='diet' && <Card>{plans?.diet ? <><div className="mb-4 flex items-center justify-between gap-3"><h2 className="font-black">{plans.diet.title}</h2>{plans.diet.publication_id&&<button onClick={()=>downloadLitePdf(plans.diet!.publication_id!,`alimentacion-imperial-v${plans.diet!.version||1}.pdf`)} className="flex items-center gap-1 rounded-lg border border-neutral-700 px-3 py-2 text-xs font-bold"><Download className="h-4 w-4"/>PDF</button>}</div><DietView plan={plans.diet}/></> : <p className="text-sm text-neutral-400">Aún no hay una alimentación publicada.</p>}</Card>}
      <SectionButton id="evolution" icon={Activity} title="Mi evolución" subtitle="Tus últimos seguimientos"/>
      {open==='evolution' && <Card>{history.length ? <div className="space-y-3">{history.map((h:any)=><div key={h.id} className="rounded-xl bg-neutral-900 p-3"><div className="flex justify-between text-xs"><span className="font-bold">{new Date(h.submitted_at).toLocaleDateString()}</span>{h.weight&&<span className="flex items-center gap-1 text-neutral-300"><Scale className="h-3 w-3"/>{h.weight} kg</span>}</div><div className="mt-2 flex flex-wrap gap-2 text-[11px] text-neutral-400">{h.nutrition_adherence!=null&&<span>Adherencia {h.nutrition_adherence}%</span>}{h.energy&&<span>Energía {h.energy}/5</span>}{h.sleep_hours&&<span>Sueño {h.sleep_hours}h</span>}{h.pain_present&&<span className="text-amber-300">Dolor {h.pain_score||0}/10 · {h.pain_area}</span>}</div></div>)}</div>:<p className="text-sm text-neutral-400">Tu evolución aparecerá después del primer seguimiento.</p>}</Card>}
    </div>
    <footer className="mt-8 flex items-start gap-2 text-[11px] leading-relaxed text-neutral-600"><HeartPulse className="mt-0.5 h-4 w-4 shrink-0"/><p>Imperial Fitness es una herramienta de acompañamiento. Si presentas dolor intenso, síntomas agudos o una condición médica, busca valoración sanitaria presencial antes de continuar.</p></footer>
  </div></main>;
}
