from __future__ import annotations

import json
import re
from dataclasses import dataclass

from fastapi import HTTPException
from sqlalchemy.orm import Session

from app.models import UserLimitation


@dataclass(frozen=True)
class SafetyPattern:
    mild: re.Pattern[str]
    moderate: re.Pattern[str]


def _rx(value: str) -> re.Pattern[str]:
    return re.compile(value, re.IGNORECASE)


PATTERNS: dict[str, SafetyPattern] = {
    "rodilla": SafetyPattern(
        mild=_rx(r"sissy|salto|burpee|sentadilla libre|zancada"),
        moderate=_rx(r"sissy|salto|burpee|sentadilla|zancada|prensa|hacka|extensi[oó]n de cu[aá]driceps|step"),
    ),
    "hombro": SafetyPattern(
        mild=_rx(r"tras de nuca|press militar|fondos|elevaci[oó]n frontal"),
        moderate=_rx(r"press|fondos|peck|fly|apertura|elevaci[oó]n|remo alto|pullover"),
    ),
    "lumbar": SafetyPattern(
        mild=_rx(r"buenos d[ií]as|peso muerto|remo inclinado|sentadilla libre"),
        moderate=_rx(r"peso muerto|buenos d[ií]as|sentadilla|remo inclinado|hiperextensi[oó]n|crunch|sit.?up|burpee"),
    ),
    "codo": SafetyPattern(
        mild=_rx(r"fondos|press franc[eé]s|extensi[oó]n de tr[ií]ceps"),
        moderate=_rx(r"fondos|tr[ií]ceps|b[ií]ceps|curl|press|extensi[oó]n de codo"),
    ),
    "muneca": SafetyPattern(
        mild=_rx(r"flexi[oó]n|push.?up|fondos|curl con barra"),
        moderate=_rx(r"press|flexi[oó]n|push.?up|fondos|plancha|curl|barra"),
    ),
    "cadera": SafetyPattern(
        mild=_rx(r"sentadilla profunda|zancada|salto"),
        moderate=_rx(r"sentadilla|zancada|prensa|hacka|hip thrust|puente|abductor|aductor|peso muerto"),
    ),
    "tobillo": SafetyPattern(
        mild=_rx(r"salto|burpee|pantorrilla de pie|caminadora"),
        moderate=_rx(r"salto|burpee|pantorrilla|zancada|sentadilla|prensa|caminadora|step"),
    ),
    "cuello": SafetyPattern(
        mild=_rx(r"encogimiento|tras de nuca|press militar"),
        moderate=_rx(r"encogimiento|tras de nuca|press militar|remo alto|sit.?up|crunch"),
    ),
}


def _extract_exercises(payload: dict) -> list[str]:
    names: list[str] = []
    for day in payload.get("days", []) if isinstance(payload.get("days"), list) else []:
        if not isinstance(day, dict):
            continue
        for exercise in day.get("exercises", []) if isinstance(day.get("exercises"), list) else []:
            if isinstance(exercise, dict):
                names.append(f"{exercise.get('name', '')} {exercise.get('notes', '')}".strip())
    return names


def validate_generated_routine_safety(db: Session, client_id: int, payload_json: str) -> None:
    """Fail closed for routines explicitly marked as generated automatically."""
    try:
        payload = json.loads(payload_json or "{}")
    except (TypeError, json.JSONDecodeError):
        raise HTTPException(status_code=422, detail="La rutina contiene un JSON inválido")

    if not isinstance(payload, dict) or not payload.get("autoGenerated"):
        return

    limitations = db.query(UserLimitation).filter(
        UserLimitation.user_id == client_id,
        UserLimitation.status == "active",
    ).all()
    high = [item for item in limitations if item.severity == "alta"]
    if high:
        zones = ", ".join(sorted({item.body_area for item in high}))
        raise HTTPException(
            status_code=422,
            detail=f"Generación automática bloqueada por limitación de severidad alta: {zones}. Requiere revisión profesional.",
        )

    conflicts: list[str] = []
    exercises = _extract_exercises(payload)
    for limitation in limitations:
        pattern_set = PATTERNS.get(limitation.body_area)
        if not pattern_set:
            continue
        pattern = pattern_set.mild if limitation.severity == "leve" else pattern_set.moderate
        for exercise in exercises:
            if pattern.search(exercise):
                conflicts.append(f"{exercise.split('.')[0][:80]} ({limitation.body_area})")

    if conflicts:
        unique = list(dict.fromkeys(conflicts))[:8]
        raise HTTPException(
            status_code=422,
            detail="La rutina automática contiene ejercicios incompatibles con limitaciones activas: " + "; ".join(unique),
        )
